Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices , along with a collection of mathematical functions to operate on these data structures . In this lesson , we will cover the basics of Numpy , focusing on arrays and vectorized operations

In [4]:
!pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   --------------------------- ------------ 8.4/12.3 MB 40.0 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 36.8 MB/s  0:00:00


In [2]:
import numpy as np

In [10]:
## Create array using numpy
## Create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [14]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape


(1, 5)

In [7]:
def sum_function(a,b):
    return a+b

print(sum_function(9,9))

18


In [ ]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape) ## there are 2 rows and 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
