Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices , along with a collection of mathematical functions to operate on these data structures . In this lesson , we will cover the basics of Numpy , focusing on arrays and vectorized operations

In [4]:
!pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   --------------------------- ------------ 8.4/12.3 MB 40.0 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 36.8 MB/s  0:00:00


In [2]:
import numpy as np

In [10]:
## Create array using numpy
## Create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [14]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape


(1, 5)

In [7]:
def sum_function(a,b):
    return a+b

print(sum_function(9,9))

18


In [ ]:
## 2d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape) ## there are 2 rows and 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [3]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
## indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## Attributes of numpy array

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape : ",arr.shape) # output : (2,3)
print("Number of dimensions:", arr.ndim) # output : 2
print("Size (number of elements) :" , arr.size) # output : 6
print("Data type : ", arr.dtype) # Output : int32 (may ber based on platform)
print("Item size (in bytes) :" , arr.itemsize) # 

Array:
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Number of dimensions: 2
Size (number of elements) : 6
Data type :  int32
Item size (in bytes) : 4


In [17]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element Wise addition
print("Addition : " , arr1+arr2)
## Element wise subtraction
print("Subtraction :" , arr1-arr2)

## Element Wise Multiplication
print("Multiplication :", arr1*arr2)
## Element wise  Division
print("Division :" , arr1/arr2)


Addition :  [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [19]:
## Universal function
arr=np.array([1,2,3,4,5,6])

## square 
print(np.sqrt(arr))

## Exponent
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
## Array slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n ", arr)

Array : 
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
arr[0][0]

1

In [23]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [27]:
arr[1:,:1]

array([[5],
       [9]])

In [28]:
## Modify array element
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [29]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [30]:
## ststistical concept -- Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data

normalized_data = (data - mean) / std_dev
print("Normalized data :" , normalized_data)

Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
 
# Mean
mean = np.mean(data)
print("Mean : " , mean)

# Median
median = np.median(data)
print("medain " , median)

# standard deviation
std_dev = np.std(data)
print("Standar Deviation : ", std_dev)

# Variance
variance = np.var(data)
print("Variance :" , variance)

TypeError: array() takes from 1 to 2 positional arguments but 10 were given

In [34]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,910])

data[data>5]

array([  6,   7,   8, 910])